apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: kubernetes-cluster-tarunkhosla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-app
        image: tarrunkhosla/i-tarunkhosla-develop:latest
        env:
          # Define the environment variable
          - name: key1
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: key1
          - name: key2
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: key2
        envFrom:
          - secretRef:
              name: my-secret
  replicas: 4
  selector:
    matchLabels:
      app: myapp
---
apiVersion: v1
kind : ConfigMap
metadata:
  name: my-configmap
  namespace: kubernetes-cluster-tarunkhosla
  labels:
     app: myapp
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind : Secret
metadata:
  name: my-secret
  namespace: kubernetes-cluster-tarunkhosla
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
type: Opaque
---

