apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-GIT_BRANCH
  namespace: kubernetes-cluster-tarunkhosla
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-GIT_BRANCH
  template:
    metadata:
      labels:
        app: myapp-GIT_BRANCH
    spec:
      containers:
      - name: my-app
        image: tarrunkhosla/i-tarunkhosla-GIT_BRANCH:latest
        env:
          # Define the environment variable
          - name: key1
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: key1
          - name: key2
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: key2
        envFrom:
          - secretRef:
              name: my-secret
  replicas: 4
  selector:
    matchLabels:
      app: myapp-GIT_BRANCH
---
apiVersion: v1
kind : ConfigMap
metadata:
  name: my-configmap-GIT_BRANCH
  namespace: kubernetes-cluster-tarunkhosla
  labels:
     app: myapp-GIT_BRANCH
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind : Secret
metadata:
  name: my-secret-GIT_BRANCH
  namespace: kubernetes-cluster-tarunkhosla
data:
  username: YWRtaW4=
  password: TmFncFJvY2tz
type: Opaque
---
