apiVersion: v1
kind: Service
metadata:
  name: my-service-GIT_BRANCH
  namespace: kubernetes-cluster-tarunkhosla
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 7100
      port: 80
  selector:
    app: myapp-GIT_BRANCH
